version: "3.6"
services:
  app:
    build:
      context: .
    volumes:
      - .:/workspace
    ports:
      - 19000:19000
      - 19002:19002
      - 19003:19003
      - 19006:19006
    environment:
      REACT_NATIVE_PACKAGER_HOSTNAME: 192.168.86.51  // this must be your computer's address on the local network
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0


